module.exports = {
    get_question: function () {

        return `
        {
            "11_7_2022": "{
                [
                    {"category":"Music",
                    "id":"622a1c397cc59eab6f950c2a",
                    "correctAnswer":"ABBA",
                    "incorrectAnswers":["In Flames","HammerFall","Katatonia"],
                    "question":"Which Swedish pop group released the song 'Thank You for the Music'?",
                    "tags":["pop_music","general_knowledge","music"],
                    "type":"Multiple Choice",
                    "difficulty":"easy",
                    "regions":[]},
                    {"category":"Science",
                    "id":"622a1c3f7cc59eab6f952389",
                    "correctAnswer":"A Turtle",
                    "incorrectAnswers":["A Volcanic Rock","A Vegetable","A Type of Cloud"],
                    "question":"What is a terrapin?",
                    "tags":["science"],
                    "type":"Multiple Choice",
                    "difficulty":"easy",
                    "regions":[]},
                    {"category":"Society & Culture",
                    "id":"622a1c3c7cc59eab6f95191a",
                    "correctAnswer":"A Pear tree",
                    "incorrectAnswers":["An Oak Tree","A Cherry Tree","A Christmas Tree"],
                    "question":"What tree is mentioned in the Christmas song 'Twelve Days of Christmas' ?",
                    "tags":["lyrics","songs","christmas","society_and_culture"],
                    "type":"Multiple Choice",
                    "difficulty":"easy",
                    "regions":[]},
                    {"category":"Food & Drink",
                    "id":"624c60dc50d1a5e051325a78",
                    "correctAnswer":"Stamppot",
                    "incorrectAnswers":["Ropa Vieja","Meat Pie","Ramen"],
                    "question":"Which of these dishes is most associated with Netherlands?",
                    "tags":["food","the_netherlands","food_and_drink"],
                    "type":"Multiple Choice",
                    "difficulty":"easy",
                    "regions":[]},
                    {"category":"Geography",
                    "id":"62374204cb85f7ce9e949da1",
                    "correctAnswer":"Russia",
                    "incorrectAnswers":["Luxembourg","Denmark","Austria"],
                    "question":"Moscow is the capital city of which country?",
                    "tags":["geography"],
                    "type":"Multiple Choice",
                    "difficulty":"easy",
                    "regions":[]}
                ]
            }", 

        },
        {
            "12_7_2022": "{
                [
                    {"category":"Music",
                    "id":"622a1c347cc59eab6f94fb91",
                    "correctAnswer":"\"Bohemian Rhapsody\" by Queen",
                    "incorrectAnswers":["\"Let it Be\" by the Beatles",
                    "\"SpongeBob SquarePants Theme\" by Painty the Pirate",
                    "\"In da Club\" by 50 Cent"],
                    "question":"Which song begins with the lyrics: \"Is this the real life? Is this just fantasy?\"?",
                    "tags":["lyrics","songs","general_knowledge","music"],
                    "type":"Multiple Choice",
                    "difficulty":"easy",
                    "regions":[]},
                    {"category":"Sport & Leisure",
                    "id":"622a1c347cc59eab6f94f891",
                    "correctAnswer":"Football",
                    "incorrectAnswers":["Hockey","Tennis","Surfing"],
                    "question":"With which sport is David Beckham associated?",
                    "tags":["people","general_knowledge","sport"],
                    "type":"Multiple Choice",
                    "difficulty":"easy",
                    "regions":[]},
                    {"category":"Science",
                    "id":"622a1c3a7cc59eab6f95101f",
                    "correctAnswer":"Blue Whale",
                    "incorrectAnswers":["African Elephant","Hippopotamus","Sperm Whale"],
                    "question":"What Is The Worlds Largest Mammal?",
                    "tags":["biology","animals","science"],
                    "type":"Multiple Choice",
                    "difficulty":"easy",
                    "regions":[]},
                    {"category":"Society & Culture",
                    "id":"622a1c357cc59eab6f94fcec",
                    "correctAnswer":"Japonic",
                    "incorrectAnswers":["Sino-Tibetan","Austroasiatic","Austronesian"],
                    "question":"The language 'Japanese' belongs to which language family?",
                    "tags":["language","society_and_culture"],
                    "type":"Multiple Choice",
                    "difficulty":"easy",
                    "regions":[]},
                    {"category":"Geography",
                    "id":"623b578cfd6c701a92118365",
                    "correctAnswer":"Israel",
                    "incorrectAnswers":["Indonesia","Brazil","Egypt"],
                    "question":"In which country would you find the City of Jerusalem?",
                    "tags":["cities","general_knowledge","geography"],
                    "type":"Multiple Choice",
                    "difficulty":"easy",
                    "regions":[]}]
            }
        }`
    }
  };