# This is a basic workflow to help you get started with Actions

name: Build & Deploy

on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: SSH Remote Commands
  # You may pin to the exact commit or the version.
  # uses: appleboy/ssh-action@1d1b21ca96111b1eb4c03c21c14ebb971d2200f6
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{secrets.SSH_HOST}}
        username: ${{secrets.SSH_USERNAME}}
        key: ${{secrets.SSH_KEY}}
        
        script: |
          echo "Deployment successful to Digital Ocean"
          cd currensee_backend  
          git pull
          npm i
          pm2 restart all
